import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {loadCharacter} from './character';
const stage=document.getElementById('stage'),selector=document.getElementById('skin'),status=document.getElementById('status');
const scene=new T.Scene();scene.background=new T.Color('#25353d');scene.add(new T.HemisphereLight('#ecfaff','#544535',2));
const sun=new T.DirectionalLight('#fff6df',2);sun.position.set(-3,5,3);scene.add(sun);
const grid=new T.GridHelper(4,20,'#527077','#34474f');grid.position.y=-.007;scene.add(grid);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;stage.appendChild(renderer.domElement);
const camera=new T.PerspectiveCamera(32,1,.005,30),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.3;controls.maxDistance=7;
let character,request,rows=[],view='quarter',last=0;
function fit(){const close=document.getElementById('detail').checked,target=new T.Vector3(0,close?1.46:1.0,0);controls.target.copy(target);const dir={front:[0,.01,1],quarter:[-.65,.12,1],side:[-1,.05,.01],back:[0,.02,-1]}[view];camera.position.copy(target).add(new T.Vector3(...dir).normalize().multiplyScalar(close?1.42:4.25));controls.update();}
async function choose(){request?.abort();request=new AbortController();const signal=request.signal;selector.disabled=true;status.hidden=false;status.textContent='Fitting skin…';const row=rows.find(r=>r.id===selector.value);document.getElementById('title').textContent=row.name;document.getElementById('reference').src='assets/skins/'+row.id+'-reference.png';document.getElementById('reference').alt=row.name+' source artwork';document.getElementById('description').textContent=row.tail?'Full C5 body with a seven-joint tapered tail.':'Full C5 body with the same proportions and equipment fit as Undead.';const url=new URL(location.href);url.searchParams.set('skin',row.id);history.replaceState(null,'',url);
 try{const equipped=document.getElementById('equipment').checked;const next=await loadCharacter({skin:row.name,head:equipped?'bone':null,armour:equipped?'leather_garb':null,weapon:equipped?'dragon_longsword':null,extra:equipped?'golden_feathers':null,magic:equipped?'fire_magic':null},t=>{if(!signal.aborted)status.textContent=t;},signal);if(signal.aborted){next.dispose();return;}character?.dispose();character=next;scene.add(character.model);character.update(0,'Idle');fit();status.hidden=true;}catch(e){if(e.name!=='AbortError')status.textContent=e.message;}finally{if(!signal.aborted)selector.disabled=false;}
}
selector.addEventListener('change',choose);document.getElementById('equipment').addEventListener('change',choose);document.getElementById('detail').addEventListener('change',fit);document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;fit();}));document.getElementById('draw').addEventListener('click',()=>character?.toggle());document.getElementById('attack').addEventListener('click',()=>character?.attack());
const resize=new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight,false);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();});resize.observe(stage);
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-(last||now))/1000);last=now;character?.update(dt,document.getElementById('motion').value);controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);
fetch('assets/skins/catalog.json').then(r=>r.json()).then(data=>{rows=data;for(const r of rows){const o=document.createElement('option');o.value=r.id;o.textContent=r.name;selector.appendChild(o);}const id=new URLSearchParams(location.search).get('skin');selector.value=rows.some(r=>r.id===id)?id:rows[0].id;choose();}).catch(e=>status.textContent=e.message);
window.addEventListener('pagehide',()=>{request?.abort();character?.dispose();resize.disconnect();controls.dispose();renderer.dispose();});
