const traits = {
  "Background": [
    { "assetId": 1631153255, "trait": "Aqua Background", "type": "Background", "total": 132, "effects": ["Increases Drown."] },
    { "assetId": 1631164569, "trait": "Blood Background", "type": "Background", "total": 144, "effects": ["Increases Bleed."] },
    { "assetId": 1631166128, "trait": "Cosmos Background", "type": "Background", "total": 53, "effects": ["Increases Intelligence", "Increases Resist."] },
    { "assetId": 1631168001, "trait": "Dungeon Background", "type": "Background", "total": 38, "effects": ["Increases Doom."] },
    { "assetId": 1631169006, "trait": "Forest Background", "type": "Background", "total": 83, "effects": ["Increases Health.", "Gain Nurture at start of battle."] },
    { "assetId": 1631170742, "trait": "Golden Background", "type": "Background", "total": 108, "effects": ["Gain Bless at start of battle."] },
    { "assetId": 1631172134, "trait": "Midnight Background", "type": "Background", "total": 105, "effects": ["Gain Focus at the start of battle."] },
    { "assetId": 1631173209, "trait": "Noir Background", "type": "Background", "total": 118, "effects": ["Increases accuracy of curse type moves."] },
    { "assetId": 1631173804, "trait": "Red Moon Background", "type": "Background", "total": 19, "effects": ["Apply Doom at the start of battle."] },
    { "assetId": 1631175041, "trait": "Sunset Background", "type": "Background", "total": 81, "effects": ["Gain Cleanse at the start of battle."] },
    { "assetId": 1631178480, "trait": "Toxic Background", "type": "Background", "total": 119, "effects": ["Increases Poison."] },
    { "assetId": 1792634314, "trait": "Valley Background", "type": "Background", "total": 40, "effects": ["Increases Speed."] },
    { "assetId": 2311097594, "trait": "Waves Background", "type": "Background", "total": 65, "effects": ["Apply Drown at the start of the battle."] }
  ],
  "Weapon": [
    { "assetId": 1631181322, "trait": "Dragon Long Sword", "type": "Weapon", "total": 63, "effects": ["Apply Burn on melee hit."] },
    { "assetId": 1631198641, "trait": "Dragon Staff", "type": "Weapon", "total": 38, "effects": ["Apply Burn at the start of battle."] },
    { "assetId": 1631201003, "trait": "Dual Katana", "type": "Weapon", "total": 79, "effects": ["Increases Speed."] },
    { "assetId": 1631202303, "trait": "Executioner Axe", "type": "Weapon", "total": 99, "effects": ["Increases Strength.", "Increases Health."] },
    { "assetId": 1631204400, "trait": "Scythe", "type": "Weapon", "total": 74, "effects": ["Apply Bleed on melee hit.", "Apply Doom on magic hit."] },
    { "assetId": 1631205295, "trait": "Shield", "type": "Weapon", "total": 89, "effects": ["Gain Shield at the start of battle."] },
    { "assetId": 1631205996, "trait": "Sickle", "type": "Weapon", "total": 78, "effects": ["Increases Nurture.", "Apply Bleed on melee hit."] },
    { "assetId": 1631207056, "trait": "Spear", "type": "Weapon", "total": 95, "effects": ["Increases Health.", "Apply Bleed on melee hit."] },
    { "assetId": 1631207955, "trait": "Trident", "type": "Weapon", "total": 112, "effects": ["Apply Drown on melee hit."] },
    { "assetId": 1792635942, "trait": "Dark Sword", "type": "Weapon", "total": 40, "effects": ["Apply Doom on melee hit."] },
    { "assetId": 1792636565, "trait": "Elf Bow", "type": "Weapon", "total": 40, "effects": ["Gain Nurture on ranged hit."] },
    
  ],
  "Magic": [
    { "assetId": 1631208827, "trait": "Dark Magic", "type": "Magic", "total": 10, "effects": ["Increases Doom."] },
    { "assetId": 1631209424, "trait": "Fire Magic", "type": "Magic", "total": 30, "effects": ["Apply Burn on magic hit."] },
    { "assetId": 1631213913, "trait": "Lightning Magic", "type": "Magic", "total": 15, "effects": ["Apply Paralyze on magic hit."] },
    { "assetId": 1631217677, "trait": "Water Magic", "type": "Magic", "total": 32, "effects": ["Increases Drown."] },
    { "assetId": 1631233542, "trait": "Ice Daggers", "type": "Magic", "total": 25, "effects": ["Apply Freeze on ranged hit."] }
  ],
  "Head": [
    { "assetId": 1631224831, "trait": "Crown of Horns", "type": "Head", "total": 18, "effects": ["Gain Doom at the start of battle.", "Gain Strengthen at the start of battle."] },
    { "assetId": 1631236045, "trait": "All Knowing", "type": "Head", "total": 61, "effects": ["Increases Intelligence."] },
    { "assetId": 1631236727, "trait": "Bone", "type": "Head", "total": 62, "effects": ["Gain Cleanse at the start of battle."] },
    { "assetId": 1631238772, "trait": "Dark Knight Helm", "type": "Head", "total": 71, "effects": ["Increases Doom."] },
    { "assetId": 1631240661, "trait": "Dragon Knight Helm", "type": "Head", "total": 30, "effects": ["Increases Health.", "Increases Burn."] },
    { "assetId": 1631243569, "trait": "Dragon", "type": "Head", "total": 129, "effects": ["Gain Burn at start of battle.", "Increases Speed."] },
    { "assetId": 1631245454, "trait": "Elder", "type": "Head", "total": 103, "effects": ["Increases Intelligence.", "Apply Freeze at the start of battle."] },
    { "assetId": 1631263106, "trait": "Gladiator Helm", "type": "Head", "total": 55, "effects": ["Increases Health.", "Increases Strength."] },
    { "assetId": 1631266132, "trait": "Purity", "type": "Head", "total": 111, "effects": ["Gain Bless at start of battle."] },
    { "assetId": 1631268297, "trait": "Scarred", "type": "Head", "total": 81, "effects": ["Increases Health.", "Increases Resist."] },
    { "assetId": 1631271286, "trait": "Snake", "type": "Head", "total": 108, "effects": ["Apply Poison at start of battle."] },
    { "assetId": 1631273225, "trait": "Undead", "type": "Head", "total": 67, "effects": ["Gain Nurture at start of battle.", "Gain Doom at start of battle."] },
    { "assetId": 1631275042, "trait": "Uni Horn", "type": "Head", "total": 104, "effects": ["Gain Bless at start of battle.", "Increases Doom."] },
    { "assetId": 1792637776, "trait": "Farmer", "type": "Head", "total": 40, "effects": ["Gain Nurture at start of battle."] },
    { "assetId": 1792640216, "trait": "Samurai", "type": "Head", "total": 40, "effects": ["Gain Focus on melee hit."] },
    { "assetId": 1935442966, "trait": "Barbarian", "type": "Head", "total": 1, "effects": ["Increases Strength.", "Decreases Accuracy."] },
    { "assetId": 2311097574, "trait": "Gold Hermes Helm", "type": "Head", "total": 10, "effects": ["Gain Empower every melee hit."] },
    { "assetId": 2311097577, "trait": "Silver Hermes Helm", "type": "Head", "total": 75, "effects": ["Gain Shield at start of battle."] },
    { "assetId": 2311097585, "trait": "Pirate Bandana", "type": "Head", "total": 65, "effects": ["Increases Speed.", "Increases Drown."] }
  ],
  "Armour": [
    { "assetId": 1631281879, "trait": "Dark Knight Armour", "type": "Armour", "total": 39, "effects": ["Gain Shield at the start of battle.", "Increases Doom."] },
    { "assetId": 1631282734, "trait": "Dragon Hunter Armour", "type": "Armour", "total": 63, "effects": ["Increases Dexterity.", "Increases Burn."] },
    { "assetId": 1631284233, "trait": "Dragon Knight Armour", "type": "Armour", "total": 29, "effects": ["Gain Shield at the start of battle.", "Increases Burn."] },
    { "assetId": 1631286848, "trait": "Gladiator Armour", "type": "Armour", "total": 47, "effects": ["Increases Health.", "Increases Strength."] },
    { "assetId": 1631293139, "trait": "Hidden One", "type": "Armour", "total": 118, "effects": ["Increases Intelligence."] },
    { "assetId": 1631296742, "trait": "Magicians Robe", "type": "Armour", "total": 84, "effects": ["Increases accuracy of magic type moves."] },
    { "assetId": 1631298825, "trait": "Pharaoh", "type": "Armour", "total": 68, "effects": ["Gain Empower at the start of battle."] },
    { "assetId": 1631299446, "trait": "Rags", "type": "Armour", "total": 157, "effects": ["Increases Dexterity."] },
    { "assetId": 1631302191, "trait": "Shinobi", "type": "Armour", "total": 78, "effects": ["Increases Speed."] },
    { "assetId": 1631305105, "trait": "Unchained", "type": "Armour", "total": 96, "effects": ["Increases Doom."] },
    { "assetId": 1642179694, "trait": "Emperor Armour", "type": "Armour", "total": 15, "effects": ["Increases Health.", "Gain Bless at the start of battle."] },
    { "assetId": 1792645489, "trait": "Elf Robe", "type": "Armour", "total": 40, "effects": ["Increases Speed.", "Increases accuracy of ranged type moves."] },
    { "assetId": 1792660153, "trait": "Leather Garb", "type": "Armour", "total": 40, "effects": ["Increases Health."] },
    { "assetId": 1806077922, "trait": "Executioner Robe", "type": "Armour", "total": 40, "effects": ["Increases Bleed."] },
    { "assetId": 2311097589, "trait": "Pirate Coat", "type": "Armour", "total": 65, "effects": ["Increases Speed.", "Increases Bleed."] }
  ],
  "Extra": [
    { "assetId": 1631307699, "trait": "Crescent Moon Earring", "type": "Extra", "total": 50, "effects": ["Increases Resist."] },
    { "assetId": 1631308577, "trait": "Dragon Fangs Earring", "type": "Extra", "total": 47, "effects": ["Increases Burn."] },
    { "assetId": 1631309418, "trait": "Fusion Pearl Earring", "type": "Extra", "total": 49, "effects": ["Increases Bless."] },
    { "assetId": 2156520477, "trait": "Tentacle Earring", "type": "Extra", "total": 45, "effects": ["Increases Drown."] },
    { "assetId": 2311097583, "trait": "Hoop Earring", "type": "Extra", "total": 65, "effects": ["Increases Health."] }
  ],
  "Skin": [
    { "trait": "Dark Skin", "type": "Skin", "champions": 195, "effects": ["Increases Health.", "Increases Strength."] },
    { "trait": "Tribal Dark Skin", "type": "Skin", "champions": 139, "effects": ["Increases Health.", "Increases Poison."] },
    { "trait": "Tribal Light Skin", "type": "Skin", "champions": 162, "effects": ["Increases Dexterity.", "Increases Poison."] },
    { "trait": "Fire Dragon", "type": "Skin", "champions": 43, "effects": ["Apply Burn at the start of battle."] },
    { "trait": "Undead", "type": "Skin", "champions": 86, "effects": ["Gain Doom at the start of battle.", "Increases Strength."] },
    { "trait": "Chameleon", "type": "Skin", "champions": 30, "effects": ["Resistance to Poison."] },
    { "trait": "Light Skin", "type": "Skin", "champions": 221, "effects": ["Increases Intelligence."] },
    { "trait": "Elder Dragon", "type": "Skin", "champions": 56, "effects": ["Resistance to Burn."] },
    { "trait": "Snake", "type": "Skin", "champions": 68, "effects": ["Gain Cleanse at the start of battle."] }
  ]
}
